name: app_koran
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: 0.13.5
  lottie: ^1.1.0
  google_sign_in: ^5.4.2
  dropdown_search: 5.0.3
  firebase_core: ^1.24.0
  firebase_auth: ^3.0.1
  get_storage: 2.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: launcher_icon
  image_path: assets/icon/icon_app.png
  ios: true
  min_sdk_android: 16
  remove_alpha_ios: true

flutter: 
  assets: 
    - assets/icon/
  uses-material-design: true

