name: app_koran
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: 0.13.5
  dropdown_search: 5.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
